name: jase
favicon: null
layout_spectrum: 0.2603427746798843
typography_spectrum: 0.1860141078941524
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9353561436291784
  lightness: 0.6751909118611366
  saturation: 0.9374513649381697
  rhythmicContrast: 0.01045424328185618
purpose: []
